import { v4 as uuidv4 } from 'uuid'

import type { Change, SchemaDiff } from '../../../shared/types/diff'
import type { MigrationScript, Statement, Warning } from '../../../shared/types/script'
import type { Column, ForeignKey, Index, Table } from '../../../shared/types/schema'

export function emitSql(schemaDiff: SchemaDiff): MigrationScript {
  const statements: Statement[] = []
  const warnings: Warning[] = []

  function s(partial: Omit<Statement, 'id'>): Statement {
    return { ...partial, id: uuidv4() }
  }

  // ── Preamble ─────────────────────────────────────────────────────────────
  statements.push(
    s({
      kind: 'preamble',
      sql: [
        `-- Migration generated by zaptar`,
        `-- Source: ${schemaDiff.source.databaseName}`,
        `-- Target: ${schemaDiff.target.databaseName}`,
        `-- Generated: ${new Date().toISOString()}`,
        ``,
        `SET FOREIGN_KEY_CHECKS = 0;`
      ].join('\n'),
      destructive: false,
      tableName: '',
      note: 'Disables FK checks for the migration session'
    })
  )

  // ── DROP FOREIGN KEY (modified tables: FKs being dropped or swapped) ─────
  for (const td of schemaDiff.modifiedTables) {
    for (const ch of td.foreignKeys) {
      if (ch.kind === 'removed' || ch.kind === 'modified') {
        const fk = ch.kind === 'removed' ? ch.before : ch.before
        statements.push(
          s({
            kind: 'drop_foreign_key',
            sql: `ALTER TABLE \`${td.name}\` DROP FOREIGN KEY \`${fk.name}\`;`,
            destructive: false,
            tableName: td.name
          })
        )
      }
    }
  }

  // ── DROP TABLE ────────────────────────────────────────────────────────────
  for (const tbl of schemaDiff.removedTables) {
    statements.push(
      s({
        kind: 'drop_table',
        sql: `DROP TABLE IF EXISTS \`${tbl.name}\`;`,
        destructive: true,
        tableName: tbl.name,
        note: 'Table present in target but absent from source — will be dropped'
      })
    )
    warnings.push({
      level: 'danger',
      message: `DROP TABLE \`${tbl.name}\` will permanently delete all rows`
    })
  }

  // ── CREATE TABLE ──────────────────────────────────────────────────────────
  for (const tbl of schemaDiff.addedTables) {
    statements.push(
      s({
        kind: 'create_table',
        sql: ddlCreateTable(tbl, false),
        destructive: false,
        tableName: tbl.name
      })
    )
  }

  // ── ALTER TABLE (modified) ────────────────────────────────────────────────
  for (const td of schemaDiff.modifiedTables) {
    // Drop indexes (except PRIMARY) before column changes
    for (const ch of td.indexes) {
      if (
        (ch.kind === 'removed' || ch.kind === 'modified') &&
        (ch.kind === 'removed' ? ch.before.name : ch.before.name) !== 'PRIMARY'
      ) {
        const idx = ch.kind === 'removed' ? ch.before : ch.before
        statements.push(
          s({
            kind: 'alter_table_drop_index',
            sql: `ALTER TABLE \`${td.name}\` DROP INDEX \`${idx.name}\`;`,
            destructive: false,
            tableName: td.name
          })
        )
      }
    }

    // Drop columns (destructive)
    for (const ch of td.columns) {
      if (ch.kind === 'removed') {
        statements.push(
          s({
            kind: 'alter_table_drop_column',
            sql: `ALTER TABLE \`${td.name}\` DROP COLUMN \`${ch.before.name}\`;`,
            destructive: true,
            tableName: td.name,
            note: `Column \`${ch.before.name}\` is absent in source — will be dropped`
          })
        )
        warnings.push({
          level: 'danger',
          message: `DROP COLUMN \`${td.name}\`.\`${ch.before.name}\` — data will be lost`
        })
      }
    }

    // Modify columns
    for (const ch of td.columns) {
      if (ch.kind === 'modified') {
        statements.push(
          s({
            kind: 'alter_table_modify_column',
            sql: `ALTER TABLE \`${td.name}\` MODIFY COLUMN ${ddlColumnDef(ch.after)};`,
            destructive: isDestructiveColumnChange(ch.before, ch.after),
            tableName: td.name
          })
        )
        if (isDestructiveColumnChange(ch.before, ch.after)) {
          warnings.push({
            level: 'warn',
            message: `MODIFY COLUMN \`${td.name}\`.\`${ch.after.name}\` may truncate data`
          })
        }
      }
    }

    // Add columns
    for (const ch of td.columns) {
      if (ch.kind === 'added') {
        statements.push(
          s({
            kind: 'alter_table_add_column',
            sql: `ALTER TABLE \`${td.name}\` ADD COLUMN ${ddlColumnDef(ch.after)};`,
            destructive: false,
            tableName: td.name
          })
        )
      }
    }

    // Add indexes (new and modified)
    for (const ch of td.indexes) {
      if (ch.kind === 'added' || ch.kind === 'modified') {
        const idx = ch.kind === 'added' ? ch.after : ch.after
        statements.push(
          s({
            kind: 'alter_table_add_index',
            sql: ddlAddIndex(td.name, idx),
            destructive: false,
            tableName: td.name
          })
        )
      }
    }

    // Table options (ENGINE, charset, collation, comment)
    if (td.optionChanges.length > 0) {
      const parts: string[] = []
      for (const oc of td.optionChanges) {
        if (oc.key === 'ENGINE') parts.push(`ENGINE = ${oc.to}`)
        else if (oc.key === 'CHARSET') parts.push(`CHARACTER SET = ${oc.to}`)
        else if (oc.key === 'COLLATION') parts.push(`COLLATE = ${oc.to}`)
        else if (oc.key === 'COMMENT')
          parts.push(`COMMENT = '${(oc.to ?? '').replace(/'/g, "\\'")}'`)
      }
      if (parts.length > 0) {
        statements.push(
          s({
            kind: 'alter_table_options',
            sql: `ALTER TABLE \`${td.name}\` ${parts.join(', ')};`,
            destructive: false,
            tableName: td.name
          })
        )
      }
    }

    // Check constraints
    for (const ch of td.checkConstraints) {
      if (ch.kind === 'removed' || ch.kind === 'modified') {
        const cc = ch.kind === 'removed' ? ch.before : ch.before
        statements.push(
          s({
            kind: 'alter_table_check_drop',
            sql: `ALTER TABLE \`${td.name}\` DROP CONSTRAINT \`${cc.name}\`;`,
            destructive: false,
            tableName: td.name
          })
        )
      }
      if (ch.kind === 'added' || ch.kind === 'modified') {
        const cc = ch.kind === 'added' ? ch.after : ch.after
        statements.push(
          s({
            kind: 'alter_table_check_add',
            sql: `ALTER TABLE \`${td.name}\` ADD CONSTRAINT \`${cc.name}\` CHECK (${cc.expression})${cc.enforced ? '' : ' NOT ENFORCED'};`,
            destructive: false,
            tableName: td.name
          })
        )
      }
    }
  }

  // ── ADD FOREIGN KEY ───────────────────────────────────────────────────────
  const addFk = (tableName: string, fk: ForeignKey): Statement =>
    s({
      kind: 'alter_table_add_foreign_key',
      sql: [
        `ALTER TABLE \`${tableName}\` ADD CONSTRAINT \`${fk.name}\``,
        `  FOREIGN KEY (${fk.columns.map((c) => `\`${c}\``).join(', ')})`,
        `  REFERENCES \`${fk.referencedTable}\` (${fk.referencedColumns.map((c) => `\`${c}\``).join(', ')})`,
        `  ON UPDATE ${fk.onUpdate} ON DELETE ${fk.onDelete};`
      ].join('\n'),
      destructive: false,
      tableName
    })

  for (const tbl of schemaDiff.addedTables) {
    for (const fk of tbl.foreignKeys) statements.push(addFk(tbl.name, fk))
  }
  for (const td of schemaDiff.modifiedTables) {
    for (const ch of td.foreignKeys) {
      if (ch.kind === 'added' || ch.kind === 'modified') {
        statements.push(addFk(td.name, ch.kind === 'added' ? ch.after : ch.after))
      }
    }
  }

  // ── Postamble ─────────────────────────────────────────────────────────────
  statements.push(
    s({ kind: 'postamble', sql: 'SET FOREIGN_KEY_CHECKS = 1;', destructive: false, tableName: '' })
  )

  return {
    generatedAt: new Date().toISOString(),
    source: { databaseName: schemaDiff.source.databaseName },
    target: { databaseName: schemaDiff.target.databaseName },
    statements,
    warnings
  }
}

// ── DDL helpers ──────────────────────────────────────────────────────────────

function ddlColumnDef(col: Column): string {
  const parts: string[] = [`\`${col.name}\``, col.dataType]
  if (col.charset) parts.push(`CHARACTER SET ${col.charset}`)
  if (col.collation) parts.push(`COLLATE ${col.collation}`)
  parts.push(col.nullable ? 'NULL' : 'NOT NULL')
  if (col.default !== null) {
    const v = col.default
    const bare = /^(CURRENT_TIMESTAMP|NOW\(\)|NULL)$/i.test(v) ? v : `'${v.replace(/'/g, "\\'")}'`
    parts.push(`DEFAULT ${bare}`)
  }
  if (col.extra) parts.push(col.extra)
  if (col.comment) parts.push(`COMMENT '${col.comment.replace(/'/g, "\\'")}'`)
  return parts.join(' ')
}

function ddlAddIndex(tableName: string, idx: Index): string {
  const colList = idx.columns
    .map((c) => `\`${c.columnName}\`${c.subPart ? `(${c.subPart})` : ''}`)
    .join(', ')
  if (idx.kind === 'primary') {
    return `ALTER TABLE \`${tableName}\` ADD PRIMARY KEY (${colList});`
  }
  const prefix =
    idx.kind === 'unique' ? 'UNIQUE INDEX' : idx.kind === 'fulltext' ? 'FULLTEXT INDEX' : 'INDEX'
  const using = idx.using ? ` USING ${idx.using}` : ''
  return `ALTER TABLE \`${tableName}\` ADD ${prefix} \`${idx.name}\` (${colList})${using};`
}

function ddlCreateTable(tbl: Table, includeFks: boolean): string {
  const lines: string[] = []
  for (const col of tbl.columns) lines.push(`  ${ddlColumnDef(col)}`)
  for (const idx of tbl.indexes) {
    const colList = idx.columns
      .map((c) => `\`${c.columnName}\`${c.subPart ? `(${c.subPart})` : ''}`)
      .join(', ')
    if (idx.kind === 'primary') lines.push(`  PRIMARY KEY (${colList})`)
    else if (idx.kind === 'unique') lines.push(`  UNIQUE KEY \`${idx.name}\` (${colList})`)
    else if (idx.kind === 'fulltext') lines.push(`  FULLTEXT KEY \`${idx.name}\` (${colList})`)
    else lines.push(`  KEY \`${idx.name}\` (${colList})`)
  }
  if (includeFks) {
    for (const fk of tbl.foreignKeys) {
      lines.push(
        `  CONSTRAINT \`${fk.name}\` FOREIGN KEY (${fk.columns.map((c) => `\`${c}\``).join(', ')}) REFERENCES \`${fk.referencedTable}\` (${fk.referencedColumns.map((c) => `\`${c}\``).join(', ')}) ON UPDATE ${fk.onUpdate} ON DELETE ${fk.onDelete}`
      )
    }
  }
  const opts = [`ENGINE=${tbl.engine}`]
  if (tbl.charset) opts.push(`DEFAULT CHARSET=${tbl.charset}`)
  if (tbl.collation) opts.push(`COLLATE=${tbl.collation}`)
  if (tbl.comment) opts.push(`COMMENT='${tbl.comment.replace(/'/g, "\\'")}'`)
  return [
    `CREATE TABLE IF NOT EXISTS \`${tbl.name}\` (`,
    lines.join(',\n'),
    `) ${opts.join(' ')};`
  ].join('\n')
}

function isDestructiveColumnChange(before: Column, after: Column): boolean {
  // Heuristic: if data type changed, flag as potentially destructive
  return before.dataType !== after.dataType
}

// Satisfy unused-import linting — Change is referenced via the diff types used in this module
export type { Change }
